export const COUNTER_COUNT_UP = 'COUNTER_COUNT_UP';
export const COUNTER_COUNT_DOWN = 'COUNTER_COUNT_DOWN';
export const COUNTER_COUNT_RESET = 'COUNTER_COUNT_RESET';

export const REPOSITORY_START_SEARCH = 'REPOSITORY_START_SEARCH';
export const REPOSITORY_SEARCH = 'REPOSITORY_SEARCH';
export const REPOSITORY_STOP_SEARCH = 'REPOSITORY_STOP_SEARCH';
